### ISSUE TITLE
Share buttons display in secondary loops (WP_Query)

### ISSUE THREAD

**Issue by JiveDig** [jaredatch/Shared-Counts#35] opened 2018-05-10 19:43 UTC
I have share icons displaying on pages on a site we manage. Home page is set to static front page, and icons are showing in our "Recent Posts" type sections of the home page. Those sections show a grid of posts via WP_Query. As a note, the text of the icons show, but there is no styling.

FWIW, this is a Genesis site.

## Current Behavior
Icons show in custom loops

## Expected Behavior
Icons should only show before/after the main loop.

## Possible Solution
I'm wondering if your hooks/filter should have an `is_main_query()` check in there. Haven't had a chance to test yet.

## Screenshots (if appropriate)
![screen shot 2018-05-10 at 3 42 16 pm](https://user-images.githubusercontent.com/540990/39890446-ccab29a8-5468-11e8-922f-109ca9345c5c.png)
![image 2018-05-10 at 3 42 33 pm](https://user-images.githubusercontent.com/540990/39890458-d364c204-5468-11e8-83d3-a4f18ba64055.png)

**Comment by jaredatch** [comment] 2018-05-10 20:40
Hey @JiveDig,

Thanks for reporting!

There's 2 things going on here I see, one is fixed and the other is not yet.

In `1.1.0` and prior we were attempted to detect Genesis by using `get_template_directory`, however this is incorrect. So what happens is Shared Counts doesn't see Genesis, so it falls back to filtering `the_content`, which is resulting in what you're reporting.

This has been corrected in the main `develop` branch (see https://github.com/jaredatch/Shared-Counts/blob/develop/includes/class-shared-counts-front.php#L56) but hasn't gone out yet since we haven't released the next update. So for now you can either manually edit that line or download the zip from GH (we haven't bumped the version number yet, so this won't conflict with our next update).

The second seperate issue is that filtering `the_content` is doing weird stuff with the excerpt, and that's definitely something we want to fix in our next release. I think what we'll do (without having actually tested this), in before we return the markup in the_content related filters, check for `in_the_loop()` - this should only output the markup/share buttons in the normal/primary look locations.

I think what's going to happen, is we may need to use this same thing for the theme location specific hooks too. Because how things stand now, even with the correct Genesis detection, it's still going to output the buttons before those excerpts. We have an `is_singular` check already, which catches some of this, but I think the issue is if there is a custom loop displayed some where on that page (using the genesis function) it is still going to output the buttons.

Hope that makes sense. Let us know if you have any questions :)

**Comment by JiveDig** [comment] 2018-05-10 20:45
Awesome that fixed it for now. I'm 100% Genesis, so if that avoid the_content filter altogether, i'm not worried about it, though I know you still have to account for it ;)

**Comment by jaredatch** [comment] 2019-04-12 15:33
If anyone knows a theme we can test where this can be reproduced, please let me know!

**Comment by JiveDig** [comment] 2019-04-12 15:49
As far as my personal issue goes, this can be closed. I only use Genesis (and Mai Theme for that matter). Just tested locally with Shared Counts set to show on posts and pages, and i have a static front page. The icons show in the front page correctly, and don't interfere with secondary loops I have on the page.

**Comment by jaredatch** [comment] 2019-04-12 16:52
@JiveDig cool, closing for now then :)

**Closed by jaredatch** 2019-04-12 16:52 UTC
Labels: bug
